server:
  port: 8110

spring:
  datasource:
    url: jdbc:mysql://146.56.191.52:3306/just_three?characterEncoding=UTF-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: 146.56.191.52
      port: 6379

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: babysoo123@gmail.com
    password: pwoz fkqc qgpt bzae
    port: '587'

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      access-key: AKIAYXUMP4RG4CDORDXS
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

my-jwt:
  issuer: just-three
  secret: hamgyeongdoMyeonghwadangKbabsangTokyoGyudong

